In [1]:
import pandas as pd

In [4]:
info = {
    "Name": ["ROiht","Akash","Aditya","harsh"],
    "cgpa": [7.7,8.0,8.5,9.0]
}

df = pd.DataFrame(info)
print(df)
df

     Name  cgpa
0   ROiht   7.7
1   Akash   8.0
2  Aditya   8.5
3   harsh   9.0

     Name  cgpa
0   ROiht   7.7
1   Akash   8.0
2  Aditya   8.5
3   harsh   9.0

In [5]:
s = pd.Series([1,2,3,4,5,6])

print(s)
print(type(s))

#index
print(s[2])

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>
3

In [6]:
s = pd.Series([1,2,3,4,5,6] , index = ["adam","bob","harsh", "jack","will","wick"])
print(s)

adam     1
bob      2
harsh    3
jack     4
will     5
wick     6
dtype: int64

In [7]:
s = pd.Series([1,2,3,4,5,"wick"] , index = ["adam","bob","harsh", "jack","will",25])
print(s)
print(s.index)
print(s["adam"])

adam        1
bob         2
harsh       3
jack        4
will        5
25       wick
dtype: object
Index(['adam', 'bob', 'harsh', 'jack', 'will', 25], dtype='object')
1

In [8]:
s1 = pd.Series([1,2,3,4,5,6])
s2 = pd.Series([10,20,30,40,50,60])
print(s1+s2)
s1[0] = 100
change_s1 = s1.drop(0)
print(s1)
print(change_s1)

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64
0    100
1      2
2      3
3      4
4      5
5      6
dtype: int64
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [9]:
df = pd.DataFrame([["Rohit",23],["JAck",25],["Eve",27]], columns = ["Name","Age"])
print(df)

    Name  Age
0  Rohit   23
1   JAck   25
2    Eve   27

In [10]:
import numpy as np 
np_arr = np.array([[1,2,3],[4,5,6]])
df = pd.DataFrame(np_arr, columns = ["A","B","C"])
print(df)

   A  B  C
0  1  2  3
1  4  5  6

In [11]:
#csv data
df = pd.read_csv("employee_data.csv")
print(df,type(df))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.core.frame.DataFrame'>

In [12]:
#Methods 
print(df.head()) #starting 5 rows
print(df.describe())
print(df.sample())
print(df.tail(2))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
             ID        Age        Salary
count  10.00000  10.000000     10.000000
mean    5.50000  32.900000  64500.000000
std     3.02765   6.674162  15182.226451
min     1.00000  25.000000  47000.000000
25%     3.25000  28.250000  51250.000000
50%     5.50000  31.000000  62500.000000
75%     7.75000  37.250000  74250.000000
max    10.00000  45.000000  91000.000000
   ID   Name  Age Department  Salary
0   1  Alice   25         HR   55000
   ID   Name  Age Department  Salary
8   9    Ian   35         IT   75000
9  10  Julia   30    Finance   60000

In [13]:
#AQI Data set 
df = pd.read_csv("globalAirQuality.csv")
df.head()
df.tail()
df.max()
df.min()

timestamp      2025-11-04 18:25:17.554219
country                                AE
city                             Auckland
latitude                          -37.814
longitude                        -123.121
pm25                                0.025
pm10                                0.061
no2                                 0.013
so2                                 0.003
o3                                  0.114
co                                    0.0
aqi                                    16
temperature                           5.0
humidity                           25.002
wind_speed                            0.5
dtype: object

In [14]:
#selecting the data 
df["city"]
df[["city","aqi"]]

df.loc[1]
df.loc[0:2]  #satrt index : end index (inclusive)

df.iloc[2]
df.iloc[0:2] # end index exclusive

df.iloc[0:2 , 2]
df.loc[0:2 , ["city","aqi","latitude","longitude"]]

       city  aqi  latitude  longitude
0  New York  108    40.713    -74.006
1  New York   90    40.713    -74.006
2  New York   84    40.713    -74.006

In [15]:
#Filtering of data
df[df["aqi"] > 100]
df[(df["aqi"] > 100)&(df["temperature"] > 30) ]
df[df["aqi"] > 100][["city","aqi"]]

           city  aqi
0      New York  108
3      New York  158
6      New York  155
7      New York  115
8      New York  121
...         ...  ...
17991    Zurich  104
17993    Zurich  153
17995    Zurich  103
17996    Zurich  105
17997    Zurich  122

[9721 rows x 2 columns]

In [16]:
#Query
aqi_val =100
df.query("aqi >100 & temperature > 30")
df.query("aqi >@aqi_val & temperature > 30")
aqi_data = df.query("aqi >@aqi_val & temperature > 30").copy()
aqi_data

,timestamp,country,city,latitude,longitude,pm25,pm10,no2,so2,o3,co,aqi,temperature,humidity,wind_speed
6,2025-11-05 00:25:17.554219,US,New York,40.713,-74.006,77.690,65.198,20.302,7.641,62.687,0.734,155,36.729,47.651,4.542
7,2025-11-05 01:25:17.554219,US,New York,40.713,-74.006,57.816,111.709,34.533,6.945,41.304,0.771,115,37.891,53.314,7.605
14,2025-11-05 08:25:17.554219,US,New York,40.713,-74.006,38.815,121.394,25.969,4.112,44.730,1.124,121,34.481,81.790,3.576
17,2025-11-05 11:25:17.554219,US,New York,40.713,-74.006,63.552,57.838,13.754,4.427,42.251,0.997,127,36.193,62.906,7.097
25,2025-11-05 19:25:17.554219,US,New York,40.713,-74.006,56.954,75.045,29.837,9.541,54.198,1.170,113,31.289,43.279,5.264
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17947,2025-11-17 13:25:17.554219,CH,Zurich,47.377,8.542,53.938,75.183,16.255,7.263,67.244,0.457,107,32.584,81.544,7.101
17950,2025-11-17 16:25:17.554219,CH,Zurich,47.377,8.542,70.255,60.620,32.081,2.065,47.803,0.852,140,36.885,34.173,1.748
17975,2025-11-18 17:25:17.554219,CH,Zurich,47.377,8.542,33.406,98.160,44.654,0.807,45.160,0.737,111,30.761,76.073,3.570
17976,2025-11-18 18:25:17.554219,CH,Zurich,47.377,8.542,73.493,89.558,9.313,4.768,51.505,0.745,146,30.909,81.573,1.024
17991,2025-11-19 09:25:17.554219,CH,Zurich,47.377,8.542,52.120,71.160,35.405,7.752,39.811,0.878,104,32.556,31.372,2.787

In [17]:
#Cleaning raw data - missing values
df = pd.read_csv("raw_data.csv")
df.isnull()

df.isnull().sum()

df.dropna() # drop rows
df.dropna(axis = 1) # drop column

df.fillna(0)

df["age"].fillna(df["age"].mean())

df.ffill()
df.bfill()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith  34.0  Canada   Female  62000.0
3    3          Alex  34.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female  51000.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6    Ahmed Khan  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     USA     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz  31.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [24]:
#Handle duplicates

df.duplicated()
df[["country","gender"]].duplicated()
df.drop_duplicates()

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [23]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0

In [31]:
#Data types 
df.dtypes
df2 = df.copy()
df2= df2.fillna(0)
df2["age"] = df2["age"].astype("int64").copy()
df2.dtypes

id           int64
name        object
age          int64
country     object
gender      object
income     float64
dtype: object

In [32]:
df2

    id          name  age country   gender   income
0    1      John Doe   29     USA     Male  55000.0
1    1      John Doe   29     USA     Male  55000.0
2    2    Jane Smith    0  Canada   Female  62000.0
3    3          Alex    0     USA  Unknown  47000.0
4    4  Maria Garcia   34   Spain   Female      0.0
5    5        Li Wei   27   China     Male  51000.0
6    6             0   45   India   Female  73000.0
7    7    Ahmed Khan   38       0     Male  68000.0
8    8    Rachel Lee   29     USA   Female  62000.0
9    9   Carlos Ruiz    0  Mexico     Male  45000.0
10  10   Emily Davis   31     USA        0  58000.0

In [43]:
aqi_data=pd.read_csv("globalAirQuality.csv")
aqi_data["timestamp"] =pd.to_datetime(aqi_data["timestamp"])
aqi_data["timestamp"].dtype

dtype('<M8[ns]')

In [40]:
data_str = pd.Series([pd.to_datetime("2026-12-31")])
type(data_str.dtypes)

numpy.dtypes.DateTime64DType

In [46]:
#Handle string 
df["gender"].str.lower()
df["gender"].str.upper()
df["gender"].str.capitalize()

0        Male
1        Male
2      Female
3     Unknown
4      Female
5        Male
6      Female
7        Male
8      Female
9        Male
10        NaN
Name: gender, dtype: object